### ISSUE TITLE
Wait sequential loading

### ISSUE THREAD

**Issue by BNastasia** [prism-checker/prism_checker#41]
3 list items are expected to be loaded. The items are loaded sequentially. First, second, third ...

`assert_page_like(@page, item_list: ['item1', 'item2', 'item3'])`

When the first element appears, an error occurs with the message: “Wrong elements count. Actual: 1.Expected: 3”.

Expected result:
The test waits until all 3 items are loaded.

**Comment by Ganglion17** [comment]
Looks like a bug

**Comment by Ganglion17** [comment]
Fixed
Please update the gem
